package com.zelix.klassmaster.util;

import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectStreamClass;
import java.util.HashMap;
import java.util.Map;

public final class SettingsObjectInputStream extends ObjectInputStream {
    private static final Map RENAMED = new HashMap();

    static {
        RENAMED.put("com.zelix._e", "com.zelix.klassmaster.ui.MethodPropertiesPanel");
        RENAMED.put("com.zelix._f", "com.zelix.klassmaster.ui.ClassModifyPanel");
        RENAMED.put("com.zelix._i", "com.zelix.klassmaster.ui.component.BevelBorderPanel");
        RENAMED.put("com.zelix._l", "com.zelix.klassmaster.ui.component.FileSelector");
        RENAMED.put("com.zelix._m", "com.zelix.klassmaster.ui.FieldModifierListModel");
        RENAMED.put("com.zelix._s", "com.zelix.klassmaster.util.IntPair");
        RENAMED.put("com.zelix._x", "com.zelix.klassmaster.ui.MemberPropertiesPanel");
        RENAMED.put("com.zelix.as", "com.zelix.UserPreferences");
        RENAMED.put("com.zelix.b8", "com.zelix.klassmaster.ui.component.MultiLineLabelCanvas");
        RENAMED.put("com.zelix.bc", "com.zelix.klassmaster.ui.component.SelfRenderingCellRenderer");
        RENAMED.put("com.zelix.bg", "com.zelix.klassmaster.proguard.ProGuardConfigParserLookaheadSuccess");
        RENAMED.put("com.zelix.bh", "com.zelix.klassmaster.config.WizardAppSettings");
        RENAMED.put("com.zelix.br", "com.zelix.klassmaster.config.TrimExcludeSettings");
        RENAMED.put("com.zelix.bs", "com.zelix.klassmaster.classfile.SerialVersionUidCalculator");
        RENAMED.put("com.zelix.bw", "com.zelix.klassmaster.obfuscator.reflection.ReflectionParamType");
        RENAMED.put("com.zelix.bx", "com.zelix.klassmaster.config.ChangeLogInputFile");
        RENAMED.put("com.zelix.cs", "com.zelix.klassmaster.classfile.ClassReferenceRole");
        RENAMED.put("com.zelix.cw", "com.zelix.klassmaster.ui.component.FilterComboBox");
        RENAMED.put("com.zelix.dp", "com.zelix.klassmaster.config.PersistedStringList");
        RENAMED.put("com.zelix.e1", "com.zelix.klassmaster.proguard.mapping.parser.ProGuardMappingToken");
        RENAMED.put("com.zelix.e3", "com.zelix.klassmaster.changelog.ChangeLogMemberKey");
        RENAMED.put("com.zelix.el", "com.zelix.klassmaster.changelog.ChangeLogMemberRecord");
        RENAMED.put("com.zelix.eq", "com.zelix.klassmaster.obfuscator.reflection.DigestCollisionException");
        RENAMED.put("com.zelix.ew", "com.zelix.klassmaster.changelog.ChangeLogClassKey");
        RENAMED.put("com.zelix.he", "com.zelix.klassmaster.exceptions.AssertionFailedException");
        RENAMED.put("com.zelix.hi", "com.zelix.klassmaster.exceptions.CorruptHierarchyException");
        RENAMED.put("com.zelix.hl", "com.zelix.klassmaster.license.LicenseExpiredException");
        RENAMED.put("com.zelix.hl6", "com.zelix.klassmaster.config.ReferenceObfIncludeStore");
        RENAMED.put("com.zelix.hm", "com.zelix.klassmaster.obfuscator.constants.LongEncryptionStorageKind");
        RENAMED.put("com.zelix.hs", "com.zelix.klassmaster.exceptions.ZkmRuntimeException");
        RENAMED.put("com.zelix.hw", "com.zelix.klassmaster.license.EvaluationExpiredException");
        RENAMED.put("com.zelix.i3", "com.zelix.klassmaster.ui.dialog.EscapeDialogCancelAction");
        RENAMED.put("com.zelix.i8", "com.zelix.klassmaster.util.SyncIndexedSet");
        RENAMED.put("com.zelix.ia", "com.zelix.klassmaster.ui.component.BannerPnl");
        RENAMED.put("com.zelix.j1", "com.zelix.klassmaster.classfile.insn.InstructionUsageFlag");
        RENAMED.put("com.zelix.j2", "com.zelix.klassmaster.ui.dialog.CopyableMessageDialog");
        RENAMED.put("com.zelix.j4", "com.zelix.klassmaster.ui.dialog.MessageBoxDialog");
        RENAMED.put("com.zelix.j5", "com.zelix.klassmaster.obfuscator.reflection.InvocationKind");
        RENAMED.put("com.zelix.jv", "com.zelix.klassmaster.ui.dialog.EscapeClosableDialog");
        RENAMED.put("com.zelix.k", "com.zelix.klassmaster.util.MutableLong");
        RENAMED.put("com.zelix.k3", "com.zelix.klassmaster.ui.dialog.OpenDialogEscapeAction");
        RENAMED.put("com.zelix.kg", "com.zelix.klassmaster.ui.component.DirectoryComboBoxRenderer");
        RENAMED.put("com.zelix.ki", "com.zelix.klassmaster.ui.component.DirectoryComboBox");
        RENAMED.put("com.zelix.km", "com.zelix.klassmaster.util.ObjectPair");
        RENAMED.put("com.zelix.ko", "com.zelix.klassmaster.util.MutableInt");
        RENAMED.put("com.zelix.m6", "com.zelix.klassmaster.ui.dialog.ExcludeParamTabPanel");
        RENAMED.put("com.zelix.m9", "com.zelix.klassmaster.ui.dialog.MethodSpecifierPanel");
        RENAMED.put("com.zelix.mb", "com.zelix.klassmaster.ui.dialog.ClassNameSpecifierPanel");
        RENAMED.put("com.zelix.mf", "com.zelix.klassmaster.obfuscator.reflection.MemberCategory");
        RENAMED.put("com.zelix.mj", "com.zelix.klassmaster.ui.dialog.PackageNameParamPanel");
        RENAMED.put("com.zelix.mk", "com.zelix.klassmaster.ui.dialog.ClassSpecifierPanel");
        RENAMED.put("com.zelix.mp", "com.zelix.klassmaster.obfuscator.reflection.ReflectionTargetKind");
        RENAMED.put("com.zelix.mv", "com.zelix.klassmaster.script.ZkmScriptParserLookaheadSuccess");
        RENAMED.put("com.zelix.mz", "com.zelix.klassmaster.ui.dialog.FieldSpecifierPanel");
        RENAMED.put("com.zelix.n0", "com.zelix.klassmaster.ui.dialog.EscapeClosingDialogBase");
        RENAMED.put("com.zelix.n4", "com.zelix.klassmaster.classfile.attribute.ExceptionRangeField");
        RENAMED.put("com.zelix.n6", "com.zelix.klassmaster.ui.dialog.FileSelectorDialog");
        RENAMED.put("com.zelix.n9", "com.zelix.klassmaster.ui.component.FileSelectorOwnedDialog");
        RENAMED.put("com.zelix.nb", "com.zelix.klassmaster.ui.dialog.TextViewerDialog");
        RENAMED.put("com.zelix.nc", "com.zelix.klassmaster.ui.dialog.AboutDialog");
        RENAMED.put("com.zelix.nd", "com.zelix.klassmaster.ui.dialog.EvaluationLicenseDialog");
        RENAMED.put("com.zelix.ne", "com.zelix.klassmaster.ui.component.UpFolderButton");
        RENAMED.put("com.zelix.nk", "com.zelix.klassmaster.ui.dialog.AbstractTextViewerDialog");
        RENAMED.put("com.zelix.np", "com.zelix.klassmaster.util.OrderedIndexedMap");
        RENAMED.put("com.zelix.nz", "com.zelix.klassmaster.ui.dialog.ClassOpenWarningsDialog");
        RENAMED.put("com.zelix.o6", "com.zelix.klassmaster.util.Triple");
        RENAMED.put("com.zelix.o8", "com.zelix.klassmaster.ui.PropertyEditFld");
        RENAMED.put("com.zelix.o_", "com.zelix.klassmaster.ui.component.FilesDisplay");
        RENAMED.put("com.zelix.od", "com.zelix.klassmaster.util.ComparableKeyValue");
        RENAMED.put("com.zelix.oe", "com.zelix.klassmaster.ui.wizard.BuildHelperScriptDialog");
        RENAMED.put("com.zelix.of", "com.zelix.klassmaster.ui.wizard.HelperInfoDialog");
        RENAMED.put("com.zelix.oi", "com.zelix.klassmaster.ui.dialog.SaveClassesDialog");
        RENAMED.put("com.zelix.ol", "com.zelix.klassmaster.ui.wizard.SaveAllStatementDialog");
        RENAMED.put("com.zelix.om", "com.zelix.klassmaster.ui.dialog.ProGuardTranslateDialog");
        RENAMED.put("com.zelix.os", "com.zelix.klassmaster.ui.wizard.ProceedConfirmDialog");
        RENAMED.put("com.zelix.ow", "com.zelix.klassmaster.ui.dialog.StackTraceTranslateDialog");
        RENAMED.put("com.zelix.ox", "com.zelix.klassmaster.ui.dialog.OpenClassesChoiceDialog");
        RENAMED.put("com.zelix.oy", "com.zelix.klassmaster.classfile.insn.SubroutineLocalsBitSet");
        RENAMED.put("com.zelix.ps", "com.zelix.klassmaster.obfuscator.string.JsrGotoKind");
        RENAMED.put("com.zelix.pw", "com.zelix.klassmaster.ui.component.ZkmScrollPane");
        RENAMED.put("com.zelix.py", "com.zelix.klassmaster.ui.dialog.ObfuscateOptionsEscapeAction");
        RENAMED.put("com.zelix.q2", "com.zelix.klassmaster.ui.dialog.TrimOptionsAction");
        RENAMED.put("com.zelix.qr", "com.zelix.klassmaster.config.TrimOptions");
        RENAMED.put("com.zelix.qz", "com.zelix.klassmaster.util.NamedHashSet");
        RENAMED.put("com.zelix.r2", "com.zelix.klassmaster.classfile.attribute.StackMapFrameKind");
        RENAMED.put("com.zelix.re", "com.zelix.klassmaster.util.Quadruple");
        RENAMED.put("com.zelix.rh", "com.zelix.klassmaster.classfile.insn.UnknownOpcodeException");
        RENAMED.put("com.zelix.rj", "com.zelix.klassmaster.util.NamedLinkedHashSet");
        RENAMED.put("com.zelix.rm", "com.zelix.klassmaster.ui.component.BorderedPanel");
        RENAMED.put("com.zelix.rn", "com.zelix.klassmaster.changelog.parser.ChangeLogTokenMgrError");
        RENAMED.put("com.zelix.s", "com.zelix.klassmaster.util.SerializableDimension");
        RENAMED.put("com.zelix.s3d", "com.zelix.klassmaster.proguard.mapping.parser.ProGuardMappingTokenMgrError");
        RENAMED.put("com.zelix.s3k", "com.zelix.klassmaster.classfile.constpool.MethodHandleRefKind");
        RENAMED.put("com.zelix.s3m", "com.zelix.klassmaster.proguard.ProGuardMappingParserLookaheadSuccess");
        RENAMED.put("com.zelix.s3p", "com.zelix.klassmaster.obfuscator.reflection.ReflectionTargetScope");
        RENAMED.put("com.zelix.s3s", "com.zelix.klassmaster.proguard.config.parser.ProGuardConfigToken");
        RENAMED.put("com.zelix.s3t", "com.zelix.klassmaster.obfuscator.reflection.ReflectionArgumentKind");
        RENAMED.put("com.zelix.s3y", "com.zelix.klassmaster.ui.dialog.ExclusionDialogCancelAction");
        RENAMED.put("com.zelix.s8", "com.zelix.klassmaster.ui.component.SplitPaneDivider");
        RENAMED.put("com.zelix.s_x", "com.zelix.klassmaster.ui.dialog.EscapeCloseAction");
        RENAMED.put("com.zelix.sfb", "com.zelix.klassmaster.proguard.mapping.parser.ProGuardMappingParseException");
        RENAMED.put("com.zelix.sfj", "com.zelix.klassmaster.changelog.ChangeLogParserLookaheadSuccess");
        RENAMED.put("com.zelix.sfw", "com.zelix.klassmaster.obfuscator.string.StringEncryptionTechnique");
        RENAMED.put("com.zelix.sg5", "com.zelix.klassmaster.ui.component.ImagePnl");
        RENAMED.put("com.zelix.sg6", "com.zelix.klassmaster.ui.component.PlatformAwareJList");
        RENAMED.put("com.zelix.sg9", "com.zelix.klassmaster.changelog.parser.ChangeLogToken");
        RENAMED.put("com.zelix.sg_", "com.zelix.klassmaster.obfuscator.reflection.MemberScope");
        RENAMED.put("com.zelix.sgb", "com.zelix.klassmaster.ui.component.FilePathList");
        RENAMED.put("com.zelix.sgh", "com.zelix.klassmaster.proguard.config.parser.ProGuardConfigParseException");
        RENAMED.put("com.zelix.sgj", "com.zelix.klassmaster.obfuscator.flow.ClassGroupingSet");
        RENAMED.put("com.zelix.sgk", "com.zelix.klassmaster.ui.component.SelfRenderingList");
        RENAMED.put("com.zelix.sgp", "com.zelix.klassmaster.classfile.attribute.TypePathKind");
        RENAMED.put("com.zelix.sgu", "com.zelix.klassmaster.xml.XmlConfigFileType");
        RENAMED.put("com.zelix.sgz", "com.zelix.klassmaster.ui.component.FileListView");
        RENAMED.put("com.zelix.sp", "com.zelix.klassmaster.config.ObfuscateOptions");
        RENAMED.put("com.zelix.srf", "com.zelix.klassmaster.ui.dialog.DialogEscapeAction");
        RENAMED.put("com.zelix.srk", "com.zelix.klassmaster.classfile.insn.LocalVariableAccessKind");
        RENAMED.put("com.zelix.sxw", "com.zelix.klassmaster.classfile.constpool.ConstantPoolTag");
        RENAMED.put("com.zelix.sye", "com.zelix.klassmaster.classfile.insn.InstructionUsageClearFlag");
        RENAMED.put("com.zelix.tc", "com.zelix.klassmaster.ui.component.NewFolderButton");
        RENAMED.put("com.zelix.tj", "com.zelix.klassmaster.ui.component.ObservingPanel");
        RENAMED.put("com.zelix.to", "com.zelix.klassmaster.archive.ArchiveSkipMode");
        RENAMED.put("com.zelix.tp", "com.zelix.klassmaster.ui.NameModifiersEditPanel");
        RENAMED.put("com.zelix.ts", "com.zelix.klassmaster.changelog.parser.ChangeLogParseException");
        RENAMED.put("com.zelix.tu", "com.zelix.klassmaster.ui.ConstantPoolEntryEditPanel");
        RENAMED.put("com.zelix.u0", "com.zelix.klassmaster.ui.dialog.FieldExcludeParameterDialog");
        RENAMED.put("com.zelix.u1", "com.zelix.klassmaster.ui.wizard.TrimOptionsWizardDialog");
        RENAMED.put("com.zelix.u2", "com.zelix.klassmaster.ui.dialog.OwnedFrameDialogBase");
        RENAMED.put("com.zelix.u3", "com.zelix.klassmaster.ui.dialog.PackageExclusionWizardDialog");
        RENAMED.put("com.zelix.u4", "com.zelix.klassmaster.ui.dialog.ExcludeParameterDialogBase");
        RENAMED.put("com.zelix.u5", "com.zelix.klassmaster.ui.dialog.ClassParameterPartDialog");
        RENAMED.put("com.zelix.u6", "com.zelix.klassmaster.ui.dialog.ExcludeParameterTypeDialog");
        RENAMED.put("com.zelix.u7", "com.zelix.klassmaster.ui.wizard.BuildHelperObfuscateOptionsDialog");
        RENAMED.put("com.zelix.u8", "com.zelix.klassmaster.ui.dialog.DeleteAttributesDialog");
        RENAMED.put("com.zelix.u9", "com.zelix.klassmaster.ui.dialog.ChangeLogListDialog");
        RENAMED.put("com.zelix.u_", "com.zelix.klassmaster.ui.dialog.InclusionParametersDialog");
        RENAMED.put("com.zelix.ua", "com.zelix.klassmaster.ui.wizard.ScriptHelperObfuscateDialog");
        RENAMED.put("com.zelix.ub", "com.zelix.klassmaster.ui.dialog.TrimExcludeTypeDialog");
        RENAMED.put("com.zelix.uc", "com.zelix.klassmaster.ui.dialog.MethodSpecifierDialog");
        RENAMED.put("com.zelix.ud", "com.zelix.klassmaster.ui.dialog.PackageExcludeDialog");
        RENAMED.put("com.zelix.ue", "com.zelix.klassmaster.ui.dialog.TrimExclusionsBaseDialog");
        RENAMED.put("com.zelix.uf", "com.zelix.klassmaster.ui.dialog.EscapeClosableFrame");
        RENAMED.put("com.zelix.ug", "com.zelix.klassmaster.ui.dialog.OpenClassesDialog");
        RENAMED.put("com.zelix.uh", "com.zelix.klassmaster.ui.dialog.ClassSuffixExcludeDialog");
        RENAMED.put("com.zelix.ui", "com.zelix.klassmaster.ui.wizard.TrimExclusionsWizardDialog");
        RENAMED.put("com.zelix.uj", "com.zelix.klassmaster.ui.dialog.ClasspathDialog");
        RENAMED.put("com.zelix.uk", "com.zelix.klassmaster.ui.dialog.IncludeParamTypeDialog");
        RENAMED.put("com.zelix.ul", "com.zelix.klassmaster.ui.dialog.TrimExclusionsDialog");
        RENAMED.put("com.zelix.um", "com.zelix.klassmaster.ui.dialog.ExclusionWizardDialogBase");
        RENAMED.put("com.zelix.un", "com.zelix.klassmaster.ui.wizard.ExcludeHelperDialog");
        RENAMED.put("com.zelix.uo", "com.zelix.klassmaster.ui.dialog.ObfuscateOptionsDialog");
        RENAMED.put("com.zelix.up", "com.zelix.klassmaster.ui.dialog.StackTraceClasspathDialog");
        RENAMED.put("com.zelix.uq", "com.zelix.klassmaster.ui.dialog.ObfuscateOptionsDialogBase");
        RENAMED.put("com.zelix.ur", "com.zelix.klassmaster.ui.wizard.WizardOpenClassesDialog");
        RENAMED.put("com.zelix.us", "com.zelix.klassmaster.ui.dialog.TrimExclusionsDialogBase");
        RENAMED.put("com.zelix.ut", "com.zelix.klassmaster.ui.ZkmMainWindow");
        RENAMED.put("com.zelix.uu", "com.zelix.klassmaster.ui.wizard.ClasspathStepDialog");
        RENAMED.put("com.zelix.uv", "com.zelix.klassmaster.ui.dialog.HelpViewerDialog");
        RENAMED.put("com.zelix.uw", "com.zelix.klassmaster.ui.wizard.TrimExcludeHelperDialog");
        RENAMED.put("com.zelix.ux", "com.zelix.klassmaster.ui.dialog.ParameterListDialog");
        RENAMED.put("com.zelix.uy", "com.zelix.klassmaster.ui.dialog.NameExclusionsDialog");
        RENAMED.put("com.zelix.uz", "com.zelix.klassmaster.ui.dialog.PathListDialog");
        RENAMED.put("com.zelix.w1", "com.zelix.klassmaster.obfuscator.reflection.AutoReflectionException");
        RENAMED.put("com.zelix.w2", "com.zelix.klassmaster.changelog.ChangeLogMergeException");
        RENAMED.put("com.zelix.w3", "com.zelix.klassmaster.exceptions.ZkmProcessingException");
        RENAMED.put("com.zelix.w4", "com.zelix.klassmaster.proguard.ProGuardIncludeException");
        RENAMED.put("com.zelix.w5", "com.zelix.klassmaster.changelog.StackTraceTranslateException");
        RENAMED.put("com.zelix.w7", "com.zelix.klassmaster.exceptions.MissingClassException");
        RENAMED.put("com.zelix.w8", "com.zelix.klassmaster.exceptions.ClassFileFormatException");
        RENAMED.put("com.zelix.w_", "com.zelix.klassmaster.exceptions.ZkmClassNotFoundException");
        RENAMED.put("com.zelix.wa", "com.zelix.klassmaster.exceptions.ClassLoadFailureException");
        RENAMED.put("com.zelix.wc", "com.zelix.klassmaster.config.ExclusionWizardSettings");
        RENAMED.put("com.zelix.wg", "com.zelix.klassmaster.exceptions.ClassLookupException");
        RENAMED.put("com.zelix.wh", "com.zelix.klassmaster.xml.XmlContentException");
        RENAMED.put("com.zelix.wi", "com.zelix.klassmaster.exceptions.ZkmException");
        RENAMED.put("com.zelix.wk", "com.zelix.klassmaster.obfuscator.constants.IntEncryptionStorageKind");
        RENAMED.put("com.zelix.wl", "com.zelix.klassmaster.archive.JadFileException");
        RENAMED.put("com.zelix.wn", "com.zelix.klassmaster.exceptions.ClassFileLoadException");
        RENAMED.put("com.zelix.wo", "com.zelix.klassmaster.exceptions.MemberNotFoundException");
        RENAMED.put("com.zelix.wq", "com.zelix.klassmaster.exceptions.InvalidEditException");
        RENAMED.put("com.zelix.wr", "com.zelix.klassmaster.changelog.TraceClassNotFoundException");
        RENAMED.put("com.zelix.wt", "com.zelix.klassmaster.exceptions.MethodAnalysisException");
        RENAMED.put("com.zelix.wv", "com.zelix.klassmaster.obfuscator.references.ReferenceObfuscationException");
        RENAMED.put("com.zelix.ww", "com.zelix.klassmaster.exceptions.StackAnalysisException");
        RENAMED.put("com.zelix.wy", "com.zelix.klassmaster.exceptions.DuplicateFieldException");
        RENAMED.put("com.zelix.x7", "com.zelix.klassmaster.classfile.attribute.TypeAnnotationTargetType");
        RENAMED.put("com.zelix.x_", "com.zelix.klassmaster.ui.component.FileListCellRenderer");
        RENAMED.put("com.zelix.xs", "com.zelix.klassmaster.ui.dialog.EscapeKeyAction");
        RENAMED.put("com.zelix.xy", "com.zelix.klassmaster.script.ZkmScriptTokenMgrError");
        RENAMED.put("com.zelix.z_", "com.zelix.klassmaster.classfile.attribute.AnnotationNameKind");
        RENAMED.put("com.zelix.zf", "com.zelix.klassmaster.script.parser.ZkmScriptParseException");
        RENAMED.put("com.zelix.zm", "com.zelix.klassmaster.ui.dialog.EvaluationDialogEscapeAction");
        RENAMED.put("com.zelix.zr", "com.zelix.klassmaster.proguard.config.parser.ProGuardConfigTokenMgrError");
        RENAMED.put("com.zelix.zy", "com.zelix.klassmaster.config.MixedCaseNamesMode");
    }

    public SettingsObjectInputStream(InputStream inputStream1) throws IOException {
        super(inputStream1);
    }

    @Override
    protected ObjectStreamClass readClassDescriptor() throws IOException, ClassNotFoundException {
        ObjectStreamClass objectStreamClass = super.readClassDescriptor();
        String string = (String) RENAMED.get(objectStreamClass.getName());
        if (string == null) {
            return objectStreamClass;
        }

        ObjectStreamClass objectStreamClass1 = ObjectStreamClass.lookup(Class.forName(string, false, SettingsObjectInputStream.class.getClassLoader()));
        return objectStreamClass1 != null ? objectStreamClass1 : objectStreamClass;
    }
}
